# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaseArch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BaseArch
  pod 'Alamofire', '~> 5.4'

  target 'BaseArchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaseArchUITests' do
    # Pods for testing
  end

end
